#theme: jekyll-theme-cayman
 
indexHeaderTitle: Senior Project

my_info:
  name: project name
  description: Description

sass:
  sass_dir: assets/css
  
permalink: /:year_:month_:day_:title

plugins:
  - jemoji

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
